baseURL = "https://community.apache.org"
title = "ASF Community Development"
languageCode = "en"

contentDir = "source"
publishDir = "target/content"

disablePathToLower = true
uglyURLs = true
enableRobotsTXT = true
disableBrowserError = true
timeout = 3000

ignoreFiles = [ ] # No files to ignore

# Enable tags but not categories
[taxonomies]
tag = "tags"

# Highlighting config. See https://help.farbox.com/pygments.html
pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsStyle = "emacs"

# Enable Git variables like commit, lastmod
enableGitInfo = true

[markup.goldmark.renderer]
unsafe = true

[blackfriday]
# hrefTargetBlank = true # We don't want everything opened in a new window
fractions = false

[frontmatter]
date = ["date", ":filename", "publishDate", "lastmod"]

[params]
# Source Code repository section
repositoryUrl = "https://github.com/apache/comdev-site"
repositorySourceBranch = "main"

# Open Graph section
title = "Apache Community Development"
description = "The Community Development project creates and provides tools, processes, and advice to help open-source software projects improve their own community health."
images = ["images/aceu19_1.jpg", "images/aceu19_2.jpg"] # Open graph images are placed in `static/images`
tags = ["OpenSource", "Community", "Apache Software Foundation"]

[social]
twitter = "ApacheCommunity"

[outputs]
home = ["html","rss"]
term = ["html"]
section = ["html","rss"]
